spring:
  application:
    name: Meu Primeiro Batch
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    jdbcUrl: jdbc:mysql://192.168.0.119:3306/MYSPRINGDATA #url para 1 datasource e jdbcUrl para varios
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    port: 8080
  main:
    allow-bean-definition-overriding: true
app:
  datasource:
    jdbcUrl: jdbc:mysql://192.168.0.119:3306/MYETDS #url para 1 datasource e jdbcUrl para varios
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver		
  paths:
    arquivos:
      entrada: /home/edu/Documentos/Desenvolvimento/estudos/dados/entrada
      emProcessamento: /home/edu/Documentos/Desenvolvimento/estudos/dados/entrada/emProcessamento
      relatorios: /home/edu/Documentos/Desenvolvimento/estudos/dados/lancamentos.csv


logging:
  file:
    name:
      /home/edu/Desenvolvimento/Java/logs/batch.log
    path:
      /home/edu/Desenvolvimento/Java/logs
  level:
    root: info



